/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.ReservaBeans;
import Model.ReservaDAO;
import Model.SalasBeans;
import Model.SalasDAO;
import com.towel.el.annotation.AnnotationResolver;
import com.towel.swing.table.ObjectTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.postgresql.util.PSQLException;
import org.postgresql.util.PSQLState;

/**
 *
 * @author 73433810
 */
public class Consulta_Reserva extends javax.swing.JFrame {

    /**
     * Creates new form Consulta_Reserva
     */
    ObjectTableModel <ReservaBeans> tableModel;
    List<SalasBeans> lista = new ArrayList<SalasBeans>();
    ReservaDAO rdao = new ReservaDAO();
    ReservaBeans rb;
    ResultSet rs = null;
    
    public Consulta_Reserva() {
        initComponents();
        preencher_salas();
        jRadioButton1.setActionCommand("todas");
        jRadioButton2.setActionCommand("porsala");
        jRadioButton3.setActionCommand("pornumero");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jRadioButton3 = new javax.swing.JRadioButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Reservas");

        jButton1.setText("Procurar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Todas");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton1MousePressed(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Por Sala");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton2MousePressed(evt);
            }
        });

        jLabel1.setText("Selecione o tipo de pesquisa e clique Procurar");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Por Número de Reserva");
        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton3MousePressed(evt);
            }
        });

        jFormattedTextField1.setEditable(false);
        jFormattedTextField1.setText("Nº da Reserva");
        jFormattedTextField1.setEnabled(false);

        jButton3.setText("Excluir");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton3)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        
        String qualselecionado;
        qualselecionado = buttonGroup1.getSelection().getActionCommand();
        System.out.println(qualselecionado);
        
        if(qualselecionado.equals("todas")){
              todas_as_reservas();
              
            }
        if(qualselecionado.equals("porsala")){
                reserva_por_sala();
            }
        if(qualselecionado.equals("pornumero")){
            reserva_por_numero();
            }
            
            
    
    }//GEN-LAST:event_jButton1MousePressed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton3MousePressed
        // TODO add your handling code here:
        jFormattedTextField1.setEditable(true);
        jFormattedTextField1.setEnabled(true);
        jFormattedTextField1.setText(null);
    }//GEN-LAST:event_jRadioButton3MousePressed

    private void jRadioButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MousePressed
        // TODO add your handling code here:
        padrao();
    }//GEN-LAST:event_jRadioButton1MousePressed

    private void jRadioButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MousePressed
        // TODO add your handling code here:
        padrao();
    }//GEN-LAST:event_jRadioButton2MousePressed

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        // ecluir reservas
        long numero = recuperar_valor();
        try {
            rdao.excluir_reserva(numero);
            jButton1MousePressed(evt);
            }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro na Exclusão", JOptionPane.ERROR_MESSAGE);   
        }               
    }//GEN-LAST:event_jButton3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta_Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta_Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta_Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta_Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta_Reserva().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

 private void todas_as_reservas(){
      this.rs = rdao.getReservas();
      montar_tabela();
  }
 private void montar_tabela(){
       AnnotationResolver resolver = new AnnotationResolver(ReservaBeans.class);
       tableModel = new ObjectTableModel<ReservaBeans>(resolver, "id,data_reserva_inicio,data_reserva_fim,descricao,funcionario,nome_sala");
        
       tableModel.setData(getData());
       jTable1.setModel(tableModel);
   }
 private List<ReservaBeans> getData() {
        List<ReservaBeans> list = new ArrayList<ReservaBeans>();
            
        try {
            while (this.rs.next()){
                String datainicio = this.rs.getString("inicio");
                String fim = this.rs.getString("fim");
                String id = this.rs.getString("id");
                long id2 = Long.parseLong(id);
                String desc = this.rs.getString("descricao");
                String funcionario = this.rs.getString("funcionario");
                String nomesala = this.rs.getString("nome");
                
                this.rb = new ReservaBeans(datainicio, fim, id2, desc, funcionario, nomesala);
                list.add(rb);
                
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
        return list;
    }
 public void preencher_salas(){
        List<SalasBeans> lis = new LinkedList<SalasBeans>();
        SalasDAO sala = new SalasDAO();
        SalasBeans sb;
        try {
            this.rs=sala.getTodas_as_Salas();
            while(this.rs.next()){
                String nome = this.rs.getString("nome");
                int id = Integer.parseInt(this.rs.getString("id"));
                sb = new SalasBeans(nome, id);
                lis.add(sb);
                jComboBox1.addItem(nome);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Fail", JOptionPane.ERROR_MESSAGE);
        }
          this.lista=lis;          
    }
 private void reserva_por_sala(){
     int id = 0;
     
     for (int i = 0; i<lista.size();i++){
           String nome = lista.get(i).getNome();
           System.out.println(nome);
           String nome_combo = (String) jComboBox1.getSelectedItem();
           if(nome.equals(nome_combo)){
               int num_id_lista = lista.get(i).getId_sala();
               System.out.println("Numero na lista: "+num_id_lista);
               id = num_id_lista;
                     
               
           }
       }
     
     this.rs = rdao.getreservas_por_salas_por_reserva(id);
     montar_tabela();
    
 }
 private void reserva_por_numero(){
     String numero = jFormattedTextField1.getText();
     int numero_reserva = 0;
     try {
         numero_reserva = Integer.parseInt(numero);
         this.rs = rdao.get_reserva_por_numero(numero_reserva);
         montar_tabela();
     } catch (NumberFormatException e) {
         JOptionPane.showMessageDialog(null, "Favor digitar apenas numeros.", "Erro na reserva ", JOptionPane.ERROR_MESSAGE);
     }
     
 }
 private void padrao(){//apenas para design
     jFormattedTextField1.setEditable(false);
     jFormattedTextField1.setEnabled(false);
     jFormattedTextField1.setText("Nº da Reserva");
 }
 public long recuperar_valor(){
     long numero_reserva = 0;
     try {
         
         int numero_linha_clicada = jTable1.getSelectedRow();
         rb = tableModel.getValue(numero_linha_clicada);
         numero_reserva = rb.getId();
         System.out.println(numero_reserva);
     }catch(ArrayIndexOutOfBoundsException ex){
         JOptionPane.showMessageDialog(null, "Selecione uma reserva", "Erro Fatal Total ", JOptionPane.ERROR_MESSAGE);
         
     }catch (NullPointerException e) {
         JOptionPane.showMessageDialog(null, "Selecione uma reserva", "Erro Fatal Total ", JOptionPane.ERROR_MESSAGE);
     }
     return numero_reserva;
 }

}
